### ISSUE TITLE
Order of Operations

### ISSUE THREAD

**Issue by obecerra-dimeline** [fantasy-toolz/mlb-predictions#3]
What is the order to run these for predictions? also receive errors when running draftkings.py 

```
draftkings.py", line 79, in get_pregame_odds
    home_team = market['outcomes'][0]['label']
                ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
KeyError: 'label'
```

**Comment by michael-petersen** [comment]
Hi,

The scripts are all automated, so in principle you don't need to run anything yourself. The most recent 'home-grown' predictions are available at [`predictions/latest.csv`](https://github.com/fantasy-toolz/mlb-predictions/blob/main/predictions/latest.csv), and the most recent lines are available at [`data/2024/odds/latest.csv`](https://github.com/fantasy-toolz/mlb-predictions/blob/main/data/2024/odds/latest.csv). There is also a frontend webpage that processes the csvs on the fly, [here](https://fantasy-toolz.github.io/predictions.html).

However, if you wanted to modify something and see the results, you can see the running order in the workflows. For the home-grown predictions, the running order is

```bash
python rundiffscraper.py
python outcomepredictions.py
python validatepredictions.py
```

And for the line scraping, the only code you need is `draftkings.py`. 

The errors were exceptions being reported in a `try...except` block, and the warnings have now been suppressed with commit 236de6b.

Closing for now, but feel free to reopen if something doesn't work as expected.
